### ISSUE TITLE
to-do

### ISSUE THREAD

**Issue by niveshull** [niveshull/wsd#1]
- [ ] embeddingi stavkov, optimalni model
   - [ ] uporaba avtomatskega razpoznavalnika (https://github.com/RSDO-DS3/SloWSD) za ročno označevanje pomenov
   - [ ] označiti pravilnost (T/F) predloga orodja
   - [ ] ravnati se po elexisovih pomenih, elexis tudi priložiti (razen v primeru, če delamo svojo zbirko pomenov, potem naredimo legendo za to)
- [ ] pozanimati se o licencah in jih urediti
- [ ] sprememba količine centrotidov glede na stopnjo polisemnosti posamezne besede
   - [ ] besede razdelimo v skupine po polisemnosti, na podlagi tega določimo, koliko stavkov na vsako besedo (lemo)
- [ ] osebni podatki
- [ ] enakopisnice in enakozvočnice itd. pod isto lemo
   - [ ] imena znotraj stavkov, ki so bila najdena kot leme, druge besedne vrste (lema izgubiti, v besedilu najdeno "o izgubi", ker je enakopisnica od ene izmd oblik glagola izgubiti)
   - [ ] neuporaba šumnikov (koža --> pade v lemo koza)
- [ ] separatorji in narekovaju (nek encodin problem? excel? pri generiranju?)
